import "./globals.css";
import { Inter } from "next/font/google";

import Navbar from "./components/Navbar";
import SmoothScrolling from "./components/SmoothScroller";
import Footer from "./components/Footer";
import ScrollToTopButton from "./components/ScrollToTop";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata = {
  title: "Core Education",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.variable}>
      <body className={` ${inter.className} antialiased`}>
        <SmoothScrolling>
          <Navbar />
          {children}
          <ScrollToTopButton />
          <Footer />
        </SmoothScrolling>
      </body>
    </html>
  );
}
